# Initial Settings
# directory:



# Model Arguments
model_args:
  model_name_or_path: microsoft/deberta-base #bert-base-cased 
  name_of_model: hp-search-deberta


# Data Training Arguments
data_args:
  task_name: ner
  dataset_name: cynthiachan/FeedRef_10pct
  return_entity_level_metrics: TRUE
  label_all_tokens: TRUE


# Training Arguments
training_args:
  output_dir: training/
  overwrite_output_dir: TRUE
  max_train_samples: 100
  max_eval_samples: 100
  report_to: wandb
  evaluation_strategy: steps
  eval_steps: 500
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  lr_min: 1e-5
  lr_max: 5e-05
  wd_min: 0.01
  wd_max: 0.3
  min_epochs: 2
  max_epochs: 8
  NUM_TRIALS: 5


# Wandb Settings
wandb:
  project: report_to_stix
  api_key: 429f12df59ecaf79b48858930860fb4ac921c2dd
  group: hp-search-deberta-gpu
  reinit: True
